### ISSUE TITLE
Dependabot alert report

### ISSUE THREAD

**Issue by louh** [usdoj-crt/crt-portal-management#1012]
Dependabot is only issuing alerts for Node.js packages detected in the crt-portal repository’s `package-lock.json` file. For this project, nearly all the affected Node.js packages are used only in our build or testing pipelines. These packages do not run on our live production or deployment instances. If an attacker were to exploit a vulnerability where Node.js packages do run, such as a development environment or on CircleCI, then we have greater security problems to worry about.

Therefore, it is not strictly necessary to update these Node.js packages in response to Dependabot alerts, even the “high” severity ones. However, it is generally good hygiene to keep our dependencies updated when we can, so a security alert is as good a prompt as any to consider updating a package.

So, with that being said, here is an overview of each alert (as of August 9, 2021), along with my proposed recommendation to resolve it.

**tar** (“high” severity)

- **Action:** update node-sass library to the latest version.
- **Possible side effects:** none
- **Note:** gulp-sass should not need to be updated, as it’s only vulnerable through a transitive dependency through node-sass.

**glob-parent** (“high” severity)

- **Action:** dismiss as “Vulnerable code is not actually used.”
- This package is used during the CSS build process and has no danger of running unknown code, and will not impact the deployed instances.
- **Note:** we do not have an option to update the library that uses this (gulp) as its maintainers have no interest in fixing this issue on their end. (Their rationale is that this is build tooling and will not run in production environments in a way that can be compromised.) You can see a number of closed issues related to this: https://github.com/gulpjs/gulp/issues?q=is%3Aissue+glob-parent+is%3Aclose

**is-svg** (“high” severity)

- **Action:** update cssnano to 4.1.11 (which specifically fixes this issue).
- **Note:** There may not be a point to update cssnano to the next major version (5.x) line, as the USWDS build process has dropped cssnano in favor of postcss-csso. Our goal should be to do the same, so as to track the USWDS’s upgrade path as closely as possible.

**trim-newlines** (“high” severity)

- **Action:** See recommendation for “tar”.

**node-notifier** (“moderate” severity)

- **Action:** remove the gulp-notify library from our repository. We don’t use it.

**yargs-parser** (“moderate” severity)

- **Action:** See recommendation for “glob-parent.”

**node-fetch** (“low” severity)

- **Action:** update pa11y-ci to the latest version.
- **Possible side effects:** Updates to this package may influence test running. Run pa11y tests to ensure that latest versions still work as expected.

**Next steps:** If these recommendations look good, the next step will be to issue one or more pull requests that take the proposed actions listed above. (If any of these updates end up being harder to do, we may consider splitting them up in different PRs so that they can be tested in isolation or make it easier to unblock the easier updates.)

**Regarding Dependabot alerts in this repo ([crt-portal-management](https://github.com/usdoj-crt/crt-portal-management/security/dependabot)):** These alerts refer to package files that no longer exist in this repository and can be safely dismissed.

New Cards Open for Tech Tasks:
- [x] Remove `gulp-notify` package - #1019
- [x] Dismiss alert for `glob-parent` (no card)
- [x] Dismiss alert for `yargs-parser` (no card)
- [x] ~Update `node-sass` package - #1020~ Superceded by #1023.
- [x] Update `cssnano` package - #1021
- [x] Update `pa11y-ci` package - #1022
- [x] Dismiss all alerts in `crt-portal-management` repository (no card)
- [x] Update to `uswds@2.5.1` package - #1023 (Note: BIG task, supercedes #1020)
- [x] Update `gulpsass@5.0.0` (no card)

**Comment by louh** [comment]
A followup to the recommended action to resolve alerts for `tar` and `trim-newlines`. I originally stated that "gulp-sass should not need to be updated, as it’s only vulnerable through a transitive dependency through node-sass." This is not entirely correct. `gulp-sass` requires a version of `node-sass` locked on the v4.x line, and this does not change even if we update `node-sass` in our `package.json`.

We can update `gulp-sass` to the v5 line which should resolve this alert, but doing so introduces breaking changes that we cannot address until `uswds` and `uswds-gulp` packages have also been updated. (This is because the `node-sass` has been deprecated, in favor of the `sass` package, which newer versions of `uswds` supports.)

**Comment by randyabramson** [comment]
Not sure how to test. Closing for now.
