### ISSUE TITLE
USWDS Testing Task Checklist

### ISSUE THREAD

**Issue by randyabramson** [usdoj-crt/crt-portal-management#1308]
- [x] Create testing grid for every link, button, function in all languages
- [x] Collect screen shots of every page in every language
- [x] Complete testing grid
- [ ] Have Terri run accessibility
- [ ] Create style guide for future use

**Comment by randyabramson** [comment]
@blaughman - start of a testing grid here: http://crtspace/sites/SP2013/II/crtcollaboration/DocumentForCollaboration/Complaint%20Portal/Testing%20Grid/Testing%20Grid.xlsx?d=w02a95d0f558f4f3ab9d1124eb06601f6

**Comment by randyabramson** [comment]
Closing this and merging tasks with #1307
