### ISSUE TITLE
Developer training sessions continuation

### ISSUE THREAD

**Issue by Jkrzy** [usdoj-crt/crt-portal-management#714]
Building on the progress from #241 and as part of ongoing transition discussions aroundFrom our last pairing session where we went over transition, we're revisiting and expanding the sessions on which we'll focus on development of skills.

- [x] CircleCI overview
- [x] CircleCI configuration (working on in #686)
- [x] NewRelic overview
- [x] NewRelic alerts and management (working on in #703)
- [ ] CSS - Codecademy intro
- [ ] Django unit testing
- [ ] Playwrite  testing scripting
- [x] Cloud.gov environment variables (maintenance mode)
- [x] Merging fixes applied directly to staging back to the develop branch ([#725](https://github.com/usdoj-crt/crt-portal/pull/725))
- [x] Installing 3rd party scripts like google tag manager
- [x] Bug investigation, remediation, and write-up
