### ISSUE TITLE
Onboarding checklist

### ISSUE THREAD

**Issue by blaughman** [usdoj-crt/crt-portal-management#947]
When a developer joins team as a new engineer 

## Pregame SYSTEMS WORK
- [x] Move project management - Github Project (LY and IL)
- [x] Sign out of zenhub (each person locally) 
- [x] Add column tags to Zenhub columns (LY) 
- [x] Archive any remaining 18F repos after transfer (LY)
- [x] Remove DOJ from 18F GitHub orgs (LY)
- [x] Push a copy of the code to https://github.com/18F/crt-django/issues and re-archive (LY)
- [ ] Make sure we have an updated system diagram - GovDelivery added - (IL and LY)
- [x] Migrate and organize docs to O365 folder - Migrate Google Docs to 0365 TEAMS (RA/BL/ER) + UPDATE WIKI with new info
- [ ] Finish adding documentation to the SSP (LY)

## Pregame PREP FOR DEVELOPER

- [x] Personnel confirmed for onboard
- [x] personnel cleared for onboard
- [x] Define roles
- [x] Review related templates for issues pull requests, etc.
- [ ] Work in regular log review in sprint cycle?
- [x] Confirm all calendar invites have a DOJ owner

## ONCE HIRED - DEV

- [x] Sections and statutes overview
- [x] Set aside time to read the documentation
- [x] Getting set up on local 
- [x] Account creation (once approved for DOJ accounts)
- [x] Get laptop and phone assigned
- [ ] Architectural decision overview 
- [ ] Disaster and recovery drill
- [ ] PI planning
- [x] Offboard 18F accounts
Invite developer to:
- [x] core meetings
- [x] documents/drive  
- [x] PA shareback doc (describing the thin slice) 
- [ ] Charter
- [x] Schedule meeting w/ engineers around technical vision, history @LindsayYoung  
- [x] create accounts @LindsayYoung 
- [x] 18F CRT GitHub team (circle and zenhub access are connected to GitHub)
- [x] CRT GitHub @dwechsle
- [x] cloud.gov
- [x] Kibana access
- [x] New Relic
- [x] Git Code Review
- [x] Local Development setup --similar to Tim
- [x] Circle CI
- [x] DOJ invite to collaborate on crt-portal repo
- [x] DOJ Account and email setup
- [x] TEAMS account
- [x] Sharepoint account
- [x] Visual Code / Sublime

## ONCE HIRED - SOFT

- [x] Tour of the app from the end user
- [x] Walkthrough vision, roadmap and thin slice  
- [x] Schedule meeting with design around end-to-end mockups  
- [x] Schedule meeting w/ design around User research, personas, etc

**Comment by LindsayYoung** [comment]
Working with @dwechsle on the GitHub transfer, we are 90% there still working on permissions, but it all was transferred over the issues and the project board moved as expected. Once we have permissions sorted, I will remove the old Drupal code, which is now archived here: https://github.com/18f/crt-portal-drupal

**Comment by louh** [comment]
@ilodidoj suggested that I add the Mac hardening steps I'm taking to this ticket. I am taking a few additional steps on the DOJ-assigned Macbook that puts it in alignment with my own employer's security obligations.

1. [Enable FileVault encrpytion.](https://support.apple.com/en-us/HT204837) (External link to Apple support documentation.)
   - Do not use the iCloud FileVault recovery. Create a local recovery key instead. Keep the recovery key in a safe location, such as 1Password, in a secure Google Drive, or both.
2. Consider installing antivirus. We use Jamf. This is TBD awaiting DOJ IT approval.

**Comment by blaughman** [comment]
Closing this card.
